# Generated by Django 3.2 on 2021-05-18 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_auto_20210518_0111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
