# Generated by Django 3.2 on 2021-05-31 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0006_auto_20210521_0115'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='checkin',
            field=models.BooleanField(default=False),
        ),
    ]
