# Generated by Django 3.2 on 2021-06-03 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0009_comments_messages_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumptions',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='services',
            name='rate',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
