# Generated by Django 3.2 on 2021-06-07 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0013_consumptions_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='desciption_es',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='services',
            name='desciption_pt',
            field=models.CharField(default=' ', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='services',
            name='message_es',
            field=models.CharField(default='Solicitud recibida', max_length=512),
        ),
        migrations.AddField(
            model_name='services',
            name='message_pt',
            field=models.CharField(default='Pedido recebido', max_length=512),
        ),
    ]
