# Generated by Django 3.2 on 2021-06-07 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0014_auto_20210607_2306'),
    ]

    operations = [
        migrations.RenameField(
            model_name='services',
            old_name='desciption_es',
            new_name='description_es',
        ),
        migrations.RenameField(
            model_name='services',
            old_name='desciption_pt',
            new_name='description_pt',
        ),
    ]
