# Generated by Django 3.2 on 2021-06-08 00:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0015_auto_20210607_2327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consumptions',
            name='description',
        ),
        migrations.AddField(
            model_name='consumptions',
            name='service',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='hotel.services'),
            preserve_default=False,
        ),
    ]
