# Generated by Django 3.2 on 2021-06-11 22:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0016_auto_20210608_0059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='messages',
            name='state',
            field=models.CharField(default='u', max_length=1),
        ),
    ]
